import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: { flex: 1, padding: 16, backgroundColor: '#f5f5f5' },
  containerCenter: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  formContainer: { width: '100%' },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 20,
    textAlign: 'center',
  },
  subtitle: {
    fontSize: 16,
    textAlign: 'center',
    marginBottom: 20,
    color: 'grey',
  },
  switchText: { color: 'blue', marginTop: 15, textAlign: 'center' },
  forgotPasswordText: {
    color: 'grey',
    marginTop: 10,
    textAlign: 'center',
    fontSize: 12,
  },
  input: {
    height: 40,
    borderColor: 'gray',
    borderWidth: 1,
    marginBottom: 12,
    paddingHorizontal: 8,
    borderRadius: 4,
    backgroundColor: '#fff',
  },
  errorText: { color: 'red', textAlign: 'center', marginBottom: 10 },
  homeHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingBottom: 10,
  },
  headerButtonLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 8,
  },
  headerButtonRight: { padding: 8, flexDirection: 'row', alignItems: 'center' },
  headerButtonText: {
    marginLeft: 5,
    color: '#007bff',
    fontSize: 16,
    fontWeight: '500',
  },
  searchInput: {
    height: 40,
    borderColor: '#ccc',
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 10,
    marginBottom: 10,
    marginHorizontal: 16,
    backgroundColor: '#fff',
  },
  categoryContainer: {
    paddingVertical: 10,
    marginBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  categoryButton: {
    paddingHorizontal: 15,
    paddingVertical: 8,
    backgroundColor: '#eee',
    borderRadius: 15,
    marginRight: 10,
  },
  categoryButtonSelected: { backgroundColor: '#007bff' },
  categoryText: { color: '#333' },
  categoryTextSelected: { color: '#fff', fontWeight: 'bold' },
  card: {
    flexDirection: 'row',
    backgroundColor: 'white',
    padding: 10,
    marginBottom: 10,
    borderRadius: 8,
    elevation: 3,
    alignItems: 'center',
  },
  cardDisabled: { opacity: 0.5, backgroundColor: '#f0f0f0' },
  cardImage: { width: 80, height: 80, borderRadius: 8 },
  cardContent: { flex: 1, marginLeft: 10, justifyContent: 'center' },
  cardTitle: { fontSize: 16, fontWeight: 'bold' },
  cardPrice: { fontSize: 14, color: 'green' },
  favoriteButton: { padding: 5, marginLeft: 10 },
  detailImage: { width: '100%', height: 250, resizeMode: 'cover' },
  detailContent: { padding: 16 },
  detailHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  detailTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    flex: 1,
    marginRight: 10,
  },
  detailDescription: { fontSize: 16, marginTop: 8, color: '#333' },
  detailStock: {
    fontSize: 14,
    color: 'gray',
    marginTop: 8,
    marginBottom: 16,
  },
  detailPrice: { fontSize: 22, color: 'green', marginBottom: 10 },
  outOfStockText: {
    fontSize: 16,
    color: 'red',
    fontWeight: 'bold',
    paddingVertical: 10,
    textAlign: 'center',
  },
  cartItem: {
    flexDirection: 'row',
    backgroundColor: '#fff',
    padding: 10,
    marginBottom: 10,
    alignItems: 'center',
    borderRadius: 8,
    elevation: 2,
  },
  cartItemImage: { width: 50, height: 50, borderRadius: 4 },
  cartItemInfo: { flex: 1, marginLeft: 10 },
  quantityControl: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
  },
  quantityText: { marginHorizontal: 10, fontSize: 16 },
  cartTotalContainer: {
    padding: 16,
    borderTopWidth: 1,
    borderColor: '#eee',
    backgroundColor: '#fff',
  },
  cartTotalText: {
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 10,
  },
  summary: { paddingVertical: 15, marginVertical: 20 },
  summaryText: { fontSize: 18, fontWeight: 'bold' },
  profileText: { fontSize: 16, marginBottom: 8 },
  adminListItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderBottomWidth: 1,
    borderColor: '#eee',
    backgroundColor: '#fff',
  },
  adminItemInfo: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 5 },
  stockText: { color: 'grey', fontSize: 12, marginLeft: 10 },
  lowStockItem: { backgroundColor: '#fff3cd' },
  lowStockText: { color: '#856404', fontWeight: 'bold' },
  adminActions: { flexDirection: 'row', gap: 10 },
  lowStockWarning: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff3cd',
    padding: 10,
    borderRadius: 5,
    marginBottom: 10,
    gap: 5,
  },
  lowStockWarningText: { color: '#856404', fontWeight: 'bold' },
  orderCard: {
    backgroundColor: 'white',
    padding: 15,
    borderRadius: 8,
    marginBottom: 10,
    elevation: 2,
    borderLeftWidth: 5,
  },
  orderCardPending: { borderLeftColor: '#ffc107' },
  orderCardCompleted: { borderLeftColor: '#28a745' },
  orderTitle: { fontSize: 16, fontWeight: 'bold', marginBottom: 5 },
  orderItems: {
    marginTop: 10,
    marginBottom: 10,
    paddingLeft: 10,
    borderLeftWidth: 1,
    borderLeftColor: '#eee',
  },
  emptyListText: { textAlign: 'center', marginTop: 30, color: 'grey' },
  confirmationTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 15,
    color: 'green',
  },
  confirmationText: {
    fontSize: 16,
    textAlign: 'center',
    marginBottom: 8,
    color: '#333',
  },
  filterContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    paddingVertical: 10,
    marginBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
    backgroundColor: '#fff',
  },
  filterButton: {
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 20,
    marginRight: 10,
    backgroundColor: '#eee',
  },
  filterButtonSelected: { backgroundColor: '#007bff' },
  filterText: { color: '#333' },
  filterTextSelected: { color: '#fff', fontWeight: 'bold' },
  statsContainer: { flex: 1, padding: 10 },
  statsTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 20,
  },
  statsCard: {
    backgroundColor: '#fff',
    borderRadius: 8,
    padding: 15,
    marginBottom: 15,
    elevation: 2,
    alignItems: 'center',
  },
  statsCardTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 10,
    color: '#555',
  },
  statsValue: { fontSize: 24, fontWeight: 'bold', color: '#007bff' },
  statsText: { fontSize: 14, color: '#333', marginBottom: 5, textAlign: 'center' },
  barLabelsContainer: {
    flexDirection: 'row',
    width: '100%',
    justifyContent: 'space-around',
    marginTop: 5,
    paddingHorizontal: 10,
  },
  barLabelText: { fontSize: 9, color: 'grey', textAlign: 'center' },
  orderActionsContainer: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginTop: 10,
    gap: 10,
  },
  snackbar: {
    position: 'absolute',
    bottom: 50,
    left: 8,
    right: 8,
    zIndex: 1,
  },
  modalCenteredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  modalView: {
    margin: 20,
    backgroundColor: 'white',
    borderRadius: 10,
    padding: 25,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    width: '80%',
  },
  modalTitle: { fontSize: 18, fontWeight: 'bold', marginBottom: 15 },
  modalText: { marginBottom: 15, textAlign: 'center', fontSize: 16 },
  modalButtonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: '100%',
    marginTop: 10,
  },
  categoryModalItem: { paddingVertical: 15, width: '100%' },
  categoryModalItemText: { textAlign: 'center', fontSize: 16 },
  categoryModalItemSelected: {
    textAlign: 'center',
    fontSize: 16,
    fontWeight: 'bold',
    color: '#007bff',
  },
  separator: { height: 1, width: '100%', backgroundColor: '#eee' },
});

export default styles;